<?php

namespace Database\Seeders;

use App\Models\Category;
use Illuminate\Database\Seeder;

class CategorySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $categories = [
            ['title'=>'realEstate', 'code'=>'01', 'parent_id'=>NULL],
            ['title'=>'land', 'code'=>'0101', 'parent_id'=>1],
            ['title'=>'commercialRealEstate', 'code'=>'0101001', 'parent_id'=>1],
            ['title'=>'commercialRealEstate', 'code'=>'0101002', 'parent_id'=>1],
            ['title'=>'commercialRealEstate', 'code'=>'0101003', 'parent_id'=>1],
            ['title'=>'commercialRealEstate', 'code'=>'0101004', 'parent_id'=>1],
            ['title'=>'commercialRealEstate', 'code'=>'0101005', 'parent_id'=>1],
            ['title'=>'commercialRealEstate', 'code'=>'0101006', 'parent_id'=>1],
            ['title'=>'commercialRealEstate', 'code'=>'0101007', 'parent_id'=>1],
            ['title'=>'commercialRealEstate', 'code'=>'0101008', 'parent_id'=>1],
            ['title'=>'other', 'code'=>'0101009', 'parent_id'=>null],
            ['title'=>'commercialRealEstate', 'code'=>'0101010', 'parent_id'=>1],
            ['title'=>'buildingsAndConstructions', 'code'=>'0101011', 'parent_id'=>73],
            ['title'=>'other', 'code'=>'0101012', 'parent_id'=>null],
            ['title'=>'other', 'code'=>'0101013', 'parent_id'=>null],
            ['title'=>'land', 'code'=>'0101014', 'parent_id'=>1],
            ['title'=>'land', 'code'=>'0101015', 'parent_id'=>1],
            ['title'=>'residentialProperty', 'code'=>'0101016', 'parent_id'=>1],
            ['title'=>'residentialProperty', 'code'=>'0101017', 'parent_id'=>1],
            ['title'=>'commercialRealEstate', 'code'=>'0102', 'parent_id'=>1],
            ['title'=>'land', 'code'=>'0103', 'parent_id'=>1],
            ['title'=>'equipment', 'code'=>'0104', 'parent_id'=>NULL],
            ['title'=>'industrialEquipment', 'code'=>'0104001', 'parent_id'=>22],
            ['title'=>'constructionEquipment', 'code'=>'0104002', 'parent_id'=>22],
            ['title'=>'constructionEquipment', 'code'=>'0104003', 'parent_id'=>22],
            ['title'=>'storageEquipment', 'code'=>'0104004', 'parent_id'=>22],
            ['title'=>'shopEquipment', 'code'=>'0104005', 'parent_id'=>22],
            ['title'=>'industrialEquipment', 'code'=>'0104006', 'parent_id'=>22],
            ['title'=>'otherEquipment', 'code'=>'0104007', 'parent_id'=>22],
            ['title'=>'metalworkingEquipment', 'code'=>'0104008', 'parent_id'=>22],
            ['title'=>'industrialEquipment', 'code'=>'0104009', 'parent_id'=>22],
            ['title'=>'foodEquipment', 'code'=>'0104010', 'parent_id'=>22],
            ['title'=>'otherEquipment', 'code'=>'0104011', 'parent_id'=>22],
            ['title'=>'otherEquipment', 'code'=>'0104012', 'parent_id'=>22],
            ['title'=>'shopEquipment', 'code'=>'0104013', 'parent_id'=>22],
            ['title'=>'shopEquipment', 'code'=>'0104014', 'parent_id'=>22],
            ['title'=>'industrialEquipment', 'code'=>'0104015', 'parent_id'=>22],
            ['title'=>'storageEquipment', 'code'=>'0104016', 'parent_id'=>22],
            ['title'=>'shopEquipment', 'code'=>'0104017', 'parent_id'=>22],
            ['title'=>'otherEquipment', 'code'=>'0104018', 'parent_id'=>22],
            ['title'=>'constructionEquipment', 'code'=>'0104019', 'parent_id'=>22],
            ['title'=>'foodEquipment', 'code'=>'0104020', 'parent_id'=>22],
            ['title'=>'industrialEquipment', 'code'=>'0104021', 'parent_id'=>22],
            ['title'=>'industrialEquipment', 'code'=>'0104022', 'parent_id'=>22],
            ['title'=>'industrialEquipment', 'code'=>'0104023', 'parent_id'=>22],
            ['title'=>'otherEquipment', 'code'=>'0104024', 'parent_id'=>22],
            ['title'=>'shopEquipment', 'code'=>'0104025', 'parent_id'=>22],
            ['title'=>'otherEquipment', 'code'=>'0104026', 'parent_id'=>22],
            ['title'=>'industrialEquipment', 'code'=>'0105', 'parent_id'=>22],
            ['title'=>'industrialEquipment', 'code'=>'0105001', 'parent_id'=>22],
            ['title'=>'storageEquipment', 'code'=>'0105002', 'parent_id'=>22],
            ['title'=>'storageEquipment', 'code'=>'0105003', 'parent_id'=>22],
            ['title'=>'otherEquipment', 'code'=>'0105004', 'parent_id'=>22],
            ['title'=>'otherEquipment', 'code'=>'0105005', 'parent_id'=>22],
            ['title'=>'otherEquipment', 'code'=>'0105006', 'parent_id'=>22],
            ['title'=>'storageEquipment', 'code'=>'0105007', 'parent_id'=>22],
            ['title'=>'shopEquipment', 'code'=>'0105008', 'parent_id'=>22],
            ['title'=>'storageEquipment', 'code'=>'0105009', 'parent_id'=>22],
            ['title'=>'transportAndEquipment', 'code'=>'0106', 'parent_id'=>22],
            ['title'=>'mototechnics', 'code'=>'0106001', 'parent_id'=>59],
            ['title'=>'airTransport', 'code'=>'0106002', 'parent_id'=>59],
            ['title'=>'passengerTransport', 'code'=>'0106003', 'parent_id'=>59],
            ['title'=>'freightTransport', 'code'=>'0106004', 'parent_id'=>59],
            ['title'=>'waterTransport', 'code'=>'0106005', 'parent_id'=>59],
            ['title'=>'freightTransport', 'code'=>'0106006', 'parent_id'=>59],
            ['title'=>'airTransport', 'code'=>'0106007', 'parent_id'=>59],
            ['title'=>'passengerTransport', 'code'=>'0106008', 'parent_id'=>59],
            ['title'=>'commercialTransport', 'code'=>'0106009', 'parent_id'=>59],
            ['title'=>'commercialTransport', 'code'=>'0106010', 'parent_id'=>59],
            ['title'=>'passengerTransport', 'code'=>'0106011', 'parent_id'=>59],
            ['title'=>'specialEquipment', 'code'=>'0106012', 'parent_id'=>59],
            ['title'=>'specialEquipment', 'code'=>'0106013', 'parent_id'=>59],
            ['title'=>'agriculturaProperty', 'code'=>'0107', 'parent_id'=>73],
            ['title'=>'animalsAndLivestock', 'code'=>'0107001', 'parent_id'=>73],
            ['title'=>'agriculturalComplex', 'code'=>'0107002', 'parent_id'=>73],
            ['title'=>'animalsAndLivestock', 'code'=>'0107003', 'parent_id'=>73],
            ['title'=>'agriculturalComplex', 'code'=>'0107004', 'parent_id'=>73],
            ['title'=>'agriculturalComplex', 'code'=>'0107005', 'parent_id'=>73],
            ['title'=>'agriculturalComplex', 'code'=>'0107006', 'parent_id'=>73],
            ['title'=>'agriculturalComplex', 'code'=>'0107007', 'parent_id'=>73],
            ['title'=>'agriculturalComplex', 'code'=>'0107008', 'parent_id'=>73],
            ['title'=>'agriculturalComplex', 'code'=>'0107009', 'parent_id'=>73],
            ['title'=>'agriculturalComplex', 'code'=>'0107010', 'parent_id'=>73],
            ['title'=>'land', 'code'=>'0108', 'parent_id'=>1],
            ['title'=>'land', 'code'=>'0108001', 'parent_id'=>1],
            ['title'=>'land', 'code'=>'0108002', 'parent_id'=>1],
            ['title'=>'land', 'code'=>'0108003', 'parent_id'=>1],
            ['title'=>'tangibles', 'code'=>'0109', 'parent_id'=>NULL],
            ['title'=>'tangibles', 'code'=>'0109001', 'parent_id'=>NULL],
            ['title'=>'tangibles', 'code'=>'0109002', 'parent_id'=>NULL],
            ['title'=>'tangibles', 'code'=>'0109002', 'parent_id'=>NULL],
            ['title'=>'tangibles', 'code'=>'0109004', 'parent_id'=>NULL],
            ['title'=>'tangibles', 'code'=>'0109005', 'parent_id'=>NULL],
            ['title'=>'tangibles', 'code'=>'0109006', 'parent_id'=>NULL],
            ['title'=>'tangibles', 'code'=>'0109007', 'parent_id'=>NULL],
            ['title'=>'tangibles', 'code'=>'0109008', 'parent_id'=>NULL],
            ['title'=>'tangibles', 'code'=>'0109009', 'parent_id'=>NULL],
            ['title'=>'tangibles', 'code'=>'0109010', 'parent_id'=>NULL],
            ['title'=>'tangibles', 'code'=>'0109011', 'parent_id'=>NULL],
            ['title'=>'tangibles', 'code'=>'0109012', 'parent_id'=>NULL],
            ['title'=>'tangibles', 'code'=>'0109013', 'parent_id'=>NULL],
            ['title'=>'tangibles', 'code'=>'0109014', 'parent_id'=>NULL],
            ['title'=>'tangibles', 'code'=>'0109015', 'parent_id'=>NULL],
            ['title'=>'tangibles', 'code'=>'0109016', 'parent_id'=>NULL],
            ['title'=>'tangibles', 'code'=>'0109017', 'parent_id'=>NULL],
            ['title'=>'tangibles', 'code'=>'0109018', 'parent_id'=>NULL],
            ['title'=>'tangibles', 'code'=>'0109019', 'parent_id'=>NULL],
            ['title'=>'tangibles', 'code'=>'0109020', 'parent_id'=>NULL],
            ['title'=>'tangibles', 'code'=>'0110', 'parent_id'=>NULL],
            ['title'=>'tangibles', 'code'=>'0110001', 'parent_id'=>NULL],
            ['title'=>'tangibles', 'code'=>'0110002', 'parent_id'=>NULL],
            ['title'=>'tangibles', 'code'=>'0110003', 'parent_id'=>NULL],
            ['title'=>'tangibles', 'code'=>'0110004', 'parent_id'=>NULL],
            ['title'=>'tangibles', 'code'=>'0110005', 'parent_id'=>NULL],
            ['title'=>'tangibles', 'code'=>'0110006', 'parent_id'=>NULL],
            ['title'=>'tangibles', 'code'=>'0110007', 'parent_id'=>NULL],
            ['title'=>'tangibles', 'code'=>'0110008', 'parent_id'=>NULL],
            ['title'=>'tangibles', 'code'=>'0110009', 'parent_id'=>NULL],
            ['title'=>'tangibles', 'code'=>'0110010', 'parent_id'=>NULL],
            ['title'=>'tangibles', 'code'=>'0110011', 'parent_id'=>NULL],
            ['title'=>'tangibles', 'code'=>'0110012', 'parent_id'=>NULL],
            ['title'=>'tangibles', 'code'=>'0110013', 'parent_id'=>NULL],
            ['title'=>'tangibles', 'code'=>'0110014', 'parent_id'=>NULL],
            ['title'=>'tangibles', 'code'=>'0110015', 'parent_id'=>NULL],
            ['title'=>'tangibles', 'code'=>'0110016', 'parent_id'=>NULL],
            ['title'=>'tangibles', 'code'=>'0110017', 'parent_id'=>NULL],
            ['title'=>'tangibles', 'code'=>'0110018', 'parent_id'=>NULL],
            ['title'=>'tangibles', 'code'=>'0110019', 'parent_id'=>NULL],
            ['title'=>'tangibles', 'code'=>'0110020', 'parent_id'=>NULL],
            ['title'=>'tangibles', 'code'=>'0110021', 'parent_id'=>NULL],
            ['title'=>'tangibles', 'code'=>'0110022', 'parent_id'=>NULL],
            ['title'=>'other', 'code'=>'02', 'parent_id'=>NULL],
            ['title'=>'other', 'code'=>'0201', 'parent_id'=>NULL],
            ['title'=>'other', 'code'=>'0202', 'parent_id'=>NULL],
            ['title'=>'other', 'code'=>'0202001', 'parent_id'=>NULL],
            ['title'=>'other', 'code'=>'0202002', 'parent_id'=>NULL],
            ['title'=>'productionLines', 'code'=>'0203', 'parent_id'=>NULL],
            ['title'=>'productionLines', 'code'=>'0203001', 'parent_id'=>NULL],
            ['title'=>'productionLines', 'code'=>'0203002', 'parent_id'=>NULL],
            ['title'=>'productionLines', 'code'=>'0203003', 'parent_id'=>NULL],
            ['title'=>'productionLines', 'code'=>'0203004', 'parent_id'=>NULL],
            ['title'=>'productionLines', 'code'=>'0203005', 'parent_id'=>NULL],
            ['title'=>'productionLines', 'code'=>'0203006', 'parent_id'=>NULL],
            ['title'=>'productionLines', 'code'=>'0203007', 'parent_id'=>NULL],
            ['title'=>'productionLines', 'code'=>'0203008', 'parent_id'=>NULL],
            ['title'=>'productionLines', 'code'=>'0203009', 'parent_id'=>NULL],
            ['title'=>'productionLines', 'code'=>'0204', 'parent_id'=>NULL],
            ['title'=>'productionLines', 'code'=>'0205', 'parent_id'=>NULL],
            ['title'=>'productionLines', 'code'=>'0205001', 'parent_id'=>NULL],
            ['title'=>'productionLines', 'code'=>'0205002', 'parent_id'=>NULL],
            ['title'=>'productionLines', 'code'=>'0205003', 'parent_id'=>NULL],
            ['title'=>'productionLines', 'code'=>'0205004', 'parent_id'=>NULL],
            ['title'=>'obligations', 'code'=>'03', 'parent_id'=>NULL],
            ['title'=>'accountsReceivable', 'code'=>'0301', 'parent_id'=>NULL],
            ['title'=>'obligations', 'code'=>'0302', 'parent_id'=>NULL],
            ['title'=>'obligations', 'code'=>'0303', 'parent_id'=>NULL],
            ['title'=>'obligations', 'code'=>'0304', 'parent_id'=>NULL],
            ['title'=>'obligations', 'code'=>'04', 'parent_id'=>NULL],
            ['title'=>'obligations', 'code'=>'0401', 'parent_id'=>NULL],
            ['title'=>'obligations', 'code'=>'0402', 'parent_id'=>NULL],
            ['title'=>'obligations', 'code'=>'0402001', 'parent_id'=>NULL],
            ['title'=>'obligations', 'code'=>'0402002', 'parent_id'=>NULL],
            ['title'=>'obligations', 'code'=>'0402003', 'parent_id'=>NULL],
            ['title'=>'obligations', 'code'=>'0402004', 'parent_id'=>NULL],
            ['title'=>'obligations', 'code'=>'0402005', 'parent_id'=>NULL],
            ['title'=>'obligations', 'code'=>'0402006', 'parent_id'=>NULL],
            ['title'=>'obligations', 'code'=>'0403', 'parent_id'=>NULL],
            ['title'=>'other', 'code'=>'99', 'parent_id'=>NULL],


        ];
        foreach($categories as $category){
            Category::create([
                'title'=>$category['title'],
                'code'=>$category['code'],
                'parent_id'=>$category['parent_id']
            ]);
        }
    }
}
