<?php

namespace Database\Seeders;

use App\Models\Category;
use Illuminate\Database\Seeder;

class CategorySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $categories = [
            ['title'=>'realEstate', 'code'=>'01', 'parent_id'=>NULL,
                'label'=>['ru'=>'Недвижимость', 'en'=>'Estate', 'zh_CN'=>'房地产']],
            ['title'=>'land', 'code'=>'0101', 'parent_id'=>1,
                'label'=>['ru'=>'Земельные участки', 'en'=>'Land', 'zh_CN'=>'地皮']],
            ['title'=>'commercialRealEstate', 'code'=>'0101001', 'parent_id'=>1,
                'label'=>['ru'=>'Недвижимость коммерческая', 'en'=>'Commercial Estate', 'zh_CN'=>'商业地产']],
            ['title'=>'commercialRealEstate', 'code'=>'0101002', 'parent_id'=>1,
                'label'=>['ru'=>'Недвижимость коммерческая', 'en'=>'Commercial Estate', 'zh_CN'=>'商业地产']],
            ['title'=>'commercialRealEstate', 'code'=>'0101003', 'parent_id'=>1,
                'label'=>['ru'=>'Недвижимость коммерческая', 'en'=>'Commercial Estate', 'zh_CN'=>'商业地产']],
            ['title'=>'commercialRealEstate', 'code'=>'0101004', 'parent_id'=>1,
                'label'=>['ru'=>'Недвижимость коммерческая', 'en'=>'Commercial Estate', 'zh_CN'=>'商业地产']],
            ['title'=>'commercialRealEstate', 'code'=>'0101005', 'parent_id'=>1,
                'label'=>['ru'=>'Недвижимость коммерческая', 'en'=>'Commercial Estate', 'zh_CN'=>'商业地产']],
            ['title'=>'commercialRealEstate', 'code'=>'0101006', 'parent_id'=>1,
                'label'=>['ru'=>'Недвижимость коммерческая', 'en'=>'Commercial Estate', 'zh_CN'=>'商业地产']],
            ['title'=>'commercialRealEstate', 'code'=>'0101007', 'parent_id'=>1,
                'label'=>['ru'=>'Недвижимость коммерческая', 'en'=>'Commercial Estate', 'zh_CN'=>'商业地产']],
            ['title'=>'commercialRealEstate', 'code'=>'0101008', 'parent_id'=>1,
                'label'=>['ru'=>'Недвижимость коммерческая', 'en'=>'Commercial Estate', 'zh_CN'=>'商业地产']],
            ['title'=>'other', 'code'=>'0101009', 'parent_id'=>null,
                'label'=>['ru'=>'Прочее', 'en'=>'Other', 'zh_CN'=>'其他']],
            ['title'=>'commercialRealEstate', 'code'=>'0101010', 'parent_id'=>1,
                'label'=>['ru'=>'Недвижимость коммерческая', 'en'=>'Commercial Estate', 'zh_CN'=>'商业地产']],
            ['title'=>'buildingsAndConstructions', 'code'=>'0101011', 'parent_id'=>73,
                'label'=>['ru'=>'Здания и сооружения', 'en'=>'Buildings and constructions', 'zh_CN'=>'建筑物及构筑物']],
            ['title'=>'other', 'code'=>'0101012', 'parent_id'=>null,
                'label'=>['ru'=>'Прочее', 'en'=>'Other', 'zh_CN'=>'其他']],
            ['title'=>'other', 'code'=>'0101013', 'parent_id'=>null,
                'label'=>['ru'=>'Прочее', 'en'=>'Other', 'zh_CN'=>'其他']],
            ['title'=>'land', 'code'=>'0101014', 'parent_id'=>1,
                'label'=>['ru'=>'Земельные участки', 'en'=>'Land', 'zh_CN'=>'地皮']],
            ['title'=>'land', 'code'=>'0101015', 'parent_id'=>1,
                'label'=>['ru'=>'Земельные участки', 'en'=>'Land', 'zh_CN'=>'地皮']],
            ['title'=>'residentialProperty', 'code'=>'0101016', 'parent_id'=>1,
                'label'=>['ru'=>'Недвижимость жилая', 'en'=>'Residential property', 'zh_CN'=>'住宅地产']],
            ['title'=>'residentialProperty', 'code'=>'0101017', 'parent_id'=>1,
                'label'=>['ru'=>'Недвижимость жилая', 'en'=>'Residential property', 'zh_CN'=>'住宅地产']],
            ['title'=>'commercialRealEstate', 'code'=>'0102', 'parent_id'=>1,
                'label'=>['ru'=>'Недвижимость коммерческая', 'en'=>'Estate', 'zh_CN'=>'房地产']],
            ['title'=>'land', 'code'=>'0103', 'parent_id'=>1,
                'label'=>['ru'=>'Земельные участки', 'en'=>'Land', 'zh_CN'=>'地皮']],
            ['title'=>'equipment', 'code'=>'0104', 'parent_id'=>NULL,
                'label'=>['ru'=>'Оборудование', 'en'=>'Equipment', 'zh_CN'=>'设备']],
            ['title'=>'industrialEquipment', 'code'=>'0104001', 'parent_id'=>22,
                'label'=>['ru'=>'Промышленное оборудование', 'en'=>'Industrial equipment', 'zh_CN'=>'工业设备']],
            ['title'=>'constructionEquipment', 'code'=>'0104002', 'parent_id'=>22,
                'label'=>['ru'=>'Строительное оборудование', 'en'=>'Construction equipment', 'zh_CN'=>'建筑设备']],
            ['title'=>'constructionEquipment', 'code'=>'0104003', 'parent_id'=>22,
                'label'=>['ru'=>'Строительное оборудование', 'en'=>'Construction equipment', 'zh_CN'=>'建筑设备']],
            ['title'=>'storageEquipment', 'code'=>'0104004', 'parent_id'=>22,
                'label'=>['ru'=>'Складское оборудование', 'en'=>'Storage equipment', 'zh_CN'=>'仓库设备']],
            ['title'=>'shopEquipment', 'code'=>'0104005', 'parent_id'=>22,
                'label'=>['ru'=>'Торговое оборудование', 'en'=>'Shop equipment', 'zh_CN'=>' 商业设备']],
            ['title'=>'industrialEquipment', 'code'=>'0104006', 'parent_id'=>22,
                'label'=>['ru'=>'Промышленное оборудование', 'en'=>'Industrial equipment', 'zh_CN'=>'工业设备']],
            ['title'=>'otherEquipment', 'code'=>'0104007', 'parent_id'=>22,
                'label'=>['ru'=>'Другое оборудование', 'en'=>'Other equipment', 'zh_CN'=>'其他设备']],
            ['title'=>'metalworkingEquipment', 'code'=>'0104008', 'parent_id'=>22,
                'label'=>['ru'=>'Металлообрабатывающее оборудование', 'en'=>'Metalworking equipment', 'zh_CN'=>'金属加工设备']],
            ['title'=>'industrialEquipment', 'code'=>'0104009', 'parent_id'=>22,
                'label'=>['ru'=>'Промышленное оборудование', 'en'=>'Industrial equipment', 'zh_CN'=>'工业设备']],
            ['title'=>'foodEquipment', 'code'=>'0104010', 'parent_id'=>22,
                'label'=>['ru'=>'Пищевое оборудование', 'en'=>'Food equipment', 'zh_CN'=>'食品设备']],
            ['title'=>'otherEquipment', 'code'=>'0104011', 'parent_id'=>22,
                'label'=>['ru'=>'Другое оборудование', 'en'=>'Other equipment', 'zh_CN'=>'其他设备']],
            ['title'=>'otherEquipment', 'code'=>'0104012', 'parent_id'=>22,
                'label'=>['ru'=>'Другое оборудование', 'en'=>'Other equipment', 'zh_CN'=>'其他设备']],
            ['title'=>'shopEquipment', 'code'=>'0104013', 'parent_id'=>22,
                'label'=>['ru'=>'Торговое оборудование', 'en'=>'Shop equipment', 'zh_CN'=>' 商业设备']],
            ['title'=>'shopEquipment', 'code'=>'0104014', 'parent_id'=>22,
                'label'=>['ru'=>'Торговое оборудование', 'en'=>'Shop equipment', 'zh_CN'=>' 商业设备']],
            ['title'=>'industrialEquipment', 'code'=>'0104015', 'parent_id'=>22,
                'label'=>['ru'=>'Промышленное оборудование', 'en'=>'Industrial equipment', 'zh_CN'=>'工业设备']],
            ['title'=>'storageEquipment', 'code'=>'0104016', 'parent_id'=>22,
                'label'=>['ru'=>'Складское оборудование', 'en'=>'Storage equipment', 'zh_CN'=>'仓库设备']],
            ['title'=>'shopEquipment', 'code'=>'0104017', 'parent_id'=>22,
                'label'=>['ru'=>'Торговое оборудование', 'en'=>'Shop equipment', 'zh_CN'=>' 商业设备']],
            ['title'=>'otherEquipment', 'code'=>'0104018', 'parent_id'=>22,
                'label'=>['ru'=>'Другое оборудование', 'en'=>'Other equipment', 'zh_CN'=>'其他设备']],
            ['title'=>'constructionEquipment', 'code'=>'0104019', 'parent_id'=>22,
                'label'=>['ru'=>'Строительное оборудование', 'en'=>'Construction equipment', 'zh_CN'=>'建筑设备']],
            ['title'=>'foodEquipment', 'code'=>'0104020', 'parent_id'=>22,
                'label'=>['ru'=>'Пищевое оборудование', 'en'=>'Food equipment', 'zh_CN'=>'食品设备']],
            ['title'=>'industrialEquipment', 'code'=>'0104021', 'parent_id'=>22,
                'label'=>['ru'=>'Промышленное оборудование', 'en'=>'Industrial equipment', 'zh_CN'=>'工业设备']],
            ['title'=>'industrialEquipment', 'code'=>'0104022', 'parent_id'=>22,
                'label'=>['ru'=>'Промышленное оборудование', 'en'=>'Industrial equipment', 'zh_CN'=>'工业设备']],
            ['title'=>'industrialEquipment', 'code'=>'0104023', 'parent_id'=>22,
                'label'=>['ru'=>'Промышленное оборудование', 'en'=>'Industrial equipment', 'zh_CN'=>'工业设备']],
            ['title'=>'otherEquipment', 'code'=>'0104024', 'parent_id'=>22,
                'label'=>['ru'=>'Другое оборудование', 'en'=>'Other equipment', 'zh_CN'=>'其他设备']],
            ['title'=>'shopEquipment', 'code'=>'0104025', 'parent_id'=>22,
                'label'=>['ru'=>'Торговое оборудование', 'en'=>'Shop equipment', 'zh_CN'=>' 商业设备']],
            ['title'=>'otherEquipment', 'code'=>'0104026', 'parent_id'=>22,
                'label'=>['ru'=>'Другое оборудование', 'en'=>'Other equipment', 'zh_CN'=>'其他设备']],
            ['title'=>'industrialEquipment', 'code'=>'0105', 'parent_id'=>22,
                'label'=>['ru'=>'Промышленное оборудование', 'en'=>'Industrial equipment', 'zh_CN'=>'工业设备']],
            ['title'=>'industrialEquipment', 'code'=>'0105001', 'parent_id'=>22,
                'label'=>['ru'=>'Промышленное оборудование', 'en'=>'Industrial equipment', 'zh_CN'=>'工业设备']],
            ['title'=>'storageEquipment', 'code'=>'0105002', 'parent_id'=>22,
                'label'=>['ru'=>'Складское оборудование', 'en'=>'Storage equipment', 'zh_CN'=>'仓库设备']],
            ['title'=>'storageEquipment', 'code'=>'0105003', 'parent_id'=>22,
                'label'=>['ru'=>'Складское оборудование', 'en'=>'Storage equipment', 'zh_CN'=>'仓库设备']],
            ['title'=>'otherEquipment', 'code'=>'0105004', 'parent_id'=>22,
                'label'=>['ru'=>'Другое оборудование', 'en'=>'Other equipment', 'zh_CN'=>'其他设备']],
            ['title'=>'otherEquipment', 'code'=>'0105005', 'parent_id'=>22,
                'label'=>['ru'=>'Другое оборудование', 'en'=>'Other equipment', 'zh_CN'=>'其他设备']],
            ['title'=>'otherEquipment', 'code'=>'0105006', 'parent_id'=>22,
                'label'=>['ru'=>'Другое оборудование', 'en'=>'Other equipment', 'zh_CN'=>'其他设备']],
            ['title'=>'storageEquipment', 'code'=>'0105007', 'parent_id'=>22,
                'label'=>['ru'=>'Складское оборудование', 'en'=>'Storage equipment', 'zh_CN'=>'仓库设备']],
            ['title'=>'shopEquipment', 'code'=>'0105008', 'parent_id'=>22,
                'label'=>['ru'=>'Торговое оборудование', 'en'=>'Shop equipment', 'zh_CN'=>' 商业设备']],
            ['title'=>'storageEquipment', 'code'=>'0105009', 'parent_id'=>22,
                'label'=>['ru'=>'Складское оборудование', 'en'=>'Storage equipment', 'zh_CN'=>'仓库设备']],
            ['title'=>'transportAndEquipment', 'code'=>'0106', 'parent_id'=>null,
                'label'=>['ru'=>'Транспорт и техника', 'en'=>'Transport and equipment', 'zh_CN'=>'运输及设备']],
            ['title'=>'mototechnics', 'code'=>'0106001', 'parent_id'=>59,
                'label'=>['ru'=>'Мототехника', 'en'=>'Mototechnics', 'zh_CN'=>'机动车辆']],
            ['title'=>'airTransport', 'code'=>'0106002', 'parent_id'=>59,
                'label'=>['ru'=>'Авиатранспорт', 'en'=>'Air transport', 'zh_CN'=>'航空运输']],
            ['title'=>'passengerTransport', 'code'=>'0106003', 'parent_id'=>59,
                'label'=>['ru'=>'Легковой транспорт', 'en'=>'Passenger transport', 'zh_CN'=>'客运服务']],
            ['title'=>'freightTransport', 'code'=>'0106004', 'parent_id'=>59,
                'label'=>['ru'=>'Грузовой транспорт', 'en'=>'Freight transport', 'zh_CN'=>'货物运输']],
            ['title'=>'waterTransport', 'code'=>'0106005', 'parent_id'=>59,
                'label'=>['ru'=>'Водный транспорт', 'en'=>'Water transport', 'zh_CN'=>'水上运输']],
            ['title'=>'freightTransport', 'code'=>'0106006', 'parent_id'=>59,
                'label'=>['ru'=>'Грузовой транспорт', 'en'=>'Freight transport', 'zh_CN'=>'货物运输']],
            ['title'=>'airTransport', 'code'=>'0106007', 'parent_id'=>59,
                'label'=>['ru'=>'Авиатранспорт', 'en'=>'Air transport', 'zh_CN'=>'航空运输']],
            ['title'=>'passengerTransport', 'code'=>'0106008', 'parent_id'=>59,
                'label'=>['ru'=>'Легковой транспорт', 'en'=>'Passenger transport', 'zh_CN'=>'客运服务']],
            ['title'=>'commercialTransport', 'code'=>'0106009', 'parent_id'=>59,
                'label'=>['ru'=>'Коммерческий транспорт', 'en'=>'Commercial transport', 'zh_CN'=>'商业运输']],
            ['title'=>'commercialTransport', 'code'=>'0106010', 'parent_id'=>59,
                'label'=>['ru'=>'Коммерческий транспорт', 'en'=>'Commercial transport', 'zh_CN'=>'商业运输']],
            ['title'=>'passengerTransport', 'code'=>'0106011', 'parent_id'=>59,
                'label'=>['ru'=>'Легковой транспорт', 'en'=>'Passenger transport', 'zh_CN'=>'客运服务']],
            ['title'=>'specialEquipment', 'code'=>'0106012', 'parent_id'=>59,
                'label'=>['ru'=>'Спецтехника', 'en'=>'Special equipment', 'zh_CN'=>'特殊设备']],
            ['title'=>'specialEquipment', 'code'=>'0106013', 'parent_id'=>59,
                'label'=>['ru'=>'Спецтехника', 'en'=>'Special equipment', 'zh_CN'=>'特殊设备']],
            ['title'=>'agriculturaProperty', 'code'=>'0107', 'parent_id'=>null,
                'label'=>['ru'=>'Сельскохозяйственное имущество', 'en'=>'Agricultura property', 'zh_CN'=>'农业财产']],
            ['title'=>'animalsAndLivestock', 'code'=>'0107001', 'parent_id'=>73,
                'label'=>['ru'=>'Животные и скот', 'en'=>'Animals and livestock', 'zh_CN'=>'动物及牲畜']],
            ['title'=>'agriculturalComplex', 'code'=>'0107002', 'parent_id'=>73,
                'label'=>['ru'=>'С/х комплекс', 'en'=>'Agricultural complex', 'zh_CN'=>'农业综合体']],
            ['title'=>'animalsAndLivestock', 'code'=>'0107003', 'parent_id'=>73,
                'label'=>['ru'=>'Животные и скот', 'en'=>'Animals and livestock', 'zh_CN'=>'动物及牲畜']],
            ['title'=>'agriculturalComplex', 'code'=>'0107004', 'parent_id'=>73,
                'label'=>['ru'=>'С/х комплекс', 'en'=>'Agricultural complex', 'zh_CN'=>'农业综合体']],
            ['title'=>'agriculturalComplex', 'code'=>'0107005', 'parent_id'=>73,
                'label'=>['ru'=>'С/х комплекс', 'en'=>'Agricultural complex', 'zh_CN'=>'农业综合体']],
            ['title'=>'agriculturalComplex', 'code'=>'0107006', 'parent_id'=>73,
                'label'=>['ru'=>'С/х комплекс', 'en'=>'Agricultural complex', 'zh_CN'=>'农业综合体']],
            ['title'=>'agriculturalComplex', 'code'=>'0107007', 'parent_id'=>73,
                'label'=>['ru'=>'С/х комплекс', 'en'=>'Agricultural complex', 'zh_CN'=>'农业综合体']],
            ['title'=>'agriculturalComplex', 'code'=>'0107008', 'parent_id'=>73,
                'label'=>['ru'=>'С/х комплекс', 'en'=>'Agricultural complex', 'zh_CN'=>'农业综合体']],
            ['title'=>'agriculturalComplex', 'code'=>'0107009', 'parent_id'=>73,
                'label'=>['ru'=>'С/х комплекс', 'en'=>'Agricultural complex', 'zh_CN'=>'农业综合体']],
            ['title'=>'agriculturalComplex', 'code'=>'0107010', 'parent_id'=>73,
                'label'=>['ru'=>'С/х комплекс', 'en'=>'Agricultural complex', 'zh_CN'=>'农业综合体']],
            ['title'=>'land', 'code'=>'0108', 'parent_id'=>1,
                'label'=>['ru'=>'Земельные участки', 'en'=>'Land', 'zh_CN'=>'地皮']],
            ['title'=>'land', 'code'=>'0108001', 'parent_id'=>1,
                'label'=>['ru'=>'Земельные участки', 'en'=>'Land', 'zh_CN'=>'地皮']],
            ['title'=>'land', 'code'=>'0108002', 'parent_id'=>1,
                'label'=>['ru'=>'Земельные участки', 'en'=>'Land', 'zh_CN'=>'地皮']],
            ['title'=>'land', 'code'=>'0108003', 'parent_id'=>1,
                'label'=>['ru'=>'Земельные участки', 'en'=>'Land', 'zh_CN'=>'地皮']],
            ['title'=>'tangibles', 'code'=>'0109', 'parent_id'=>NULL,
                'label'=>['ru'=>'Товарно-материальные ценности', 'en'=>'Tangibles', 'zh_CN'=>'存货项目']],
            ['title'=>'tangibles', 'code'=>'0109001', 'parent_id'=>NULL,
                'label'=>['ru'=>'Товарно-материальные ценности', 'en'=>'Tangibles', 'zh_CN'=>'存货项目']],
            ['title'=>'tangibles', 'code'=>'0109002', 'parent_id'=>NULL,
                'label'=>['ru'=>'Товарно-материальные ценности', 'en'=>'Tangibles', 'zh_CN'=>'存货项目']],
            ['title'=>'tangibles', 'code'=>'0109003', 'parent_id'=>NULL,
                'label'=>['ru'=>'Товарно-материальные ценности', 'en'=>'Tangibles', 'zh_CN'=>'存货项目']],
            ['title'=>'tangibles', 'code'=>'0109004', 'parent_id'=>NULL,
                'label'=>['ru'=>'Товарно-материальные ценности', 'en'=>'Tangibles', 'zh_CN'=>'存货项目']],
            ['title'=>'tangibles', 'code'=>'0109005', 'parent_id'=>NULL,
                'label'=>['ru'=>'Товарно-материальные ценности', 'en'=>'Tangibles', 'zh_CN'=>'存货项目']],
            ['title'=>'tangibles', 'code'=>'0109006', 'parent_id'=>NULL,
                'label'=>['ru'=>'Товарно-материальные ценности', 'en'=>'Tangibles', 'zh_CN'=>'存货项目']],
            ['title'=>'tangibles', 'code'=>'0109007', 'parent_id'=>NULL,
                'label'=>['ru'=>'Товарно-материальные ценности', 'en'=>'Tangibles', 'zh_CN'=>'存货项目']],
            ['title'=>'tangibles', 'code'=>'0109008', 'parent_id'=>NULL,
                'label'=>['ru'=>'Товарно-материальные ценности', 'en'=>'Tangibles', 'zh_CN'=>'存货项目']],
            ['title'=>'tangibles', 'code'=>'0109009', 'parent_id'=>NULL,
                'label'=>['ru'=>'Товарно-материальные ценности', 'en'=>'Tangibles', 'zh_CN'=>'存货项目']],
            ['title'=>'tangibles', 'code'=>'0109010', 'parent_id'=>NULL,
                'label'=>['ru'=>'Товарно-материальные ценности', 'en'=>'Tangibles', 'zh_CN'=>'存货项目']],
            ['title'=>'tangibles', 'code'=>'0109011', 'parent_id'=>NULL,
                'label'=>['ru'=>'Товарно-материальные ценности', 'en'=>'Tangibles', 'zh_CN'=>'存货项目']],
            ['title'=>'tangibles', 'code'=>'0109012', 'parent_id'=>NULL,
                'label'=>['ru'=>'Товарно-материальные ценности', 'en'=>'Tangibles', 'zh_CN'=>'存货项目']],
            ['title'=>'tangibles', 'code'=>'0109013', 'parent_id'=>NULL,
                'label'=>['ru'=>'Товарно-материальные ценности', 'en'=>'Tangibles', 'zh_CN'=>'存货项目']],
            ['title'=>'tangibles', 'code'=>'0109014', 'parent_id'=>NULL,
                'label'=>['ru'=>'Товарно-материальные ценности', 'en'=>'Tangibles', 'zh_CN'=>'存货项目']],
            ['title'=>'tangibles', 'code'=>'0109015', 'parent_id'=>NULL,
                'label'=>['ru'=>'Товарно-материальные ценности', 'en'=>'Tangibles', 'zh_CN'=>'存货项目']],
            ['title'=>'tangibles', 'code'=>'0109016', 'parent_id'=>NULL,
                'label'=>['ru'=>'Товарно-материальные ценности', 'en'=>'Tangibles', 'zh_CN'=>'存货项目']],
            ['title'=>'tangibles', 'code'=>'0109017', 'parent_id'=>NULL,
                'label'=>['ru'=>'Товарно-материальные ценности', 'en'=>'Tangibles', 'zh_CN'=>'存货项目']],
            ['title'=>'tangibles', 'code'=>'0109018', 'parent_id'=>NULL,
                'label'=>['ru'=>'Товарно-материальные ценности', 'en'=>'Tangibles', 'zh_CN'=>'存货项目']],
            ['title'=>'tangibles', 'code'=>'0109019', 'parent_id'=>NULL,
                'label'=>['ru'=>'Товарно-материальные ценности', 'en'=>'Tangibles', 'zh_CN'=>'存货项目']],
            ['title'=>'tangibles', 'code'=>'0109020', 'parent_id'=>NULL,
                'label'=>['ru'=>'Товарно-материальные ценности', 'en'=>'Tangibles', 'zh_CN'=>'存货项目']],
            ['title'=>'tangibles', 'code'=>'0110', 'parent_id'=>NULL,
                'label'=>['ru'=>'Товарно-материальные ценности', 'en'=>'Tangibles', 'zh_CN'=>'存货项目']],
            ['title'=>'tangibles', 'code'=>'0110001', 'parent_id'=>NULL,
                'label'=>['ru'=>'Товарно-материальные ценности', 'en'=>'Tangibles', 'zh_CN'=>'存货项目']],
            ['title'=>'tangibles', 'code'=>'0110002', 'parent_id'=>NULL,
                'label'=>['ru'=>'Товарно-материальные ценности', 'en'=>'Tangibles', 'zh_CN'=>'存货项目']],
            ['title'=>'tangibles', 'code'=>'0110003', 'parent_id'=>NULL,
                'label'=>['ru'=>'Товарно-материальные ценности', 'en'=>'Tangibles', 'zh_CN'=>'存货项目']],
            ['title'=>'tangibles', 'code'=>'0110004', 'parent_id'=>NULL,
                'label'=>['ru'=>'Товарно-материальные ценности', 'en'=>'Tangibles', 'zh_CN'=>'存货项目']],
            ['title'=>'tangibles', 'code'=>'0110005', 'parent_id'=>NULL,
                'label'=>['ru'=>'Товарно-материальные ценности', 'en'=>'Tangibles', 'zh_CN'=>'存货项目']],
            ['title'=>'tangibles', 'code'=>'0110006', 'parent_id'=>NULL,
                'label'=>['ru'=>'Товарно-материальные ценности', 'en'=>'Tangibles', 'zh_CN'=>'存货项目']],
            ['title'=>'tangibles', 'code'=>'0110007', 'parent_id'=>NULL,
                'label'=>['ru'=>'Товарно-материальные ценности', 'en'=>'Tangibles', 'zh_CN'=>'存货项目']],
            ['title'=>'tangibles', 'code'=>'0110008', 'parent_id'=>NULL,
                'label'=>['ru'=>'Товарно-материальные ценности', 'en'=>'Tangibles', 'zh_CN'=>'存货项目']],
            ['title'=>'tangibles', 'code'=>'0110009', 'parent_id'=>NULL,
                'label'=>['ru'=>'Товарно-материальные ценности', 'en'=>'Tangibles', 'zh_CN'=>'存货项目']],
            ['title'=>'tangibles', 'code'=>'0110010', 'parent_id'=>NULL,
                'label'=>['ru'=>'Товарно-материальные ценности', 'en'=>'Tangibles', 'zh_CN'=>'存货项目']],
            ['title'=>'tangibles', 'code'=>'0110011', 'parent_id'=>NULL,
                'label'=>['ru'=>'Товарно-материальные ценности', 'en'=>'Tangibles', 'zh_CN'=>'存货项目']],
            ['title'=>'tangibles', 'code'=>'0110012', 'parent_id'=>NULL,
                'label'=>['ru'=>'Товарно-материальные ценности', 'en'=>'Tangibles', 'zh_CN'=>'存货项目']],
            ['title'=>'tangibles', 'code'=>'0110013', 'parent_id'=>NULL,
                'label'=>['ru'=>'Товарно-материальные ценности', 'en'=>'Tangibles', 'zh_CN'=>'存货项目']],
            ['title'=>'tangibles', 'code'=>'0110014', 'parent_id'=>NULL,
                'label'=>['ru'=>'Товарно-материальные ценности', 'en'=>'Tangibles', 'zh_CN'=>'存货项目']],
            ['title'=>'tangibles', 'code'=>'0110015', 'parent_id'=>NULL,
                'label'=>['ru'=>'Товарно-материальные ценности', 'en'=>'Tangibles', 'zh_CN'=>'存货项目']],
            ['title'=>'tangibles', 'code'=>'0110016', 'parent_id'=>NULL,
                'label'=>['ru'=>'Товарно-материальные ценности', 'en'=>'Tangibles', 'zh_CN'=>'存货项目']],
            ['title'=>'tangibles', 'code'=>'0110017', 'parent_id'=>NULL,
                'label'=>['ru'=>'Товарно-материальные ценности', 'en'=>'Tangibles', 'zh_CN'=>'存货项目']],
            ['title'=>'tangibles', 'code'=>'0110018', 'parent_id'=>NULL,
                'label'=>['ru'=>'Товарно-материальные ценности', 'en'=>'Tangibles', 'zh_CN'=>'存货项目']],
            ['title'=>'tangibles', 'code'=>'0110019', 'parent_id'=>NULL,
                'label'=>['ru'=>'Товарно-материальные ценности', 'en'=>'Tangibles', 'zh_CN'=>'存货项目']],
            ['title'=>'tangibles', 'code'=>'0110020', 'parent_id'=>NULL,
                'label'=>['ru'=>'Товарно-материальные ценности', 'en'=>'Tangibles', 'zh_CN'=>'存货项目']],
            ['title'=>'tangibles', 'code'=>'0110021', 'parent_id'=>NULL,
                'label'=>['ru'=>'Товарно-материальные ценности', 'en'=>'Tangibles', 'zh_CN'=>'存货项目']],
            ['title'=>'tangibles', 'code'=>'0110022', 'parent_id'=>NULL,
                'label'=>['ru'=>'Товарно-материальные ценности', 'en'=>'Tangibles', 'zh_CN'=>'存货项目']],
            ['title'=>'other', 'code'=>'02', 'parent_id'=>NULL,
                'label'=>['ru'=>'Прочее', 'en'=>'Other', 'zh_CN'=>'其他']],
            ['title'=>'other', 'code'=>'0201', 'parent_id'=>NULL,
                'label'=>['ru'=>'Прочее', 'en'=>'Other', 'zh_CN'=>'其他']],
            ['title'=>'other', 'code'=>'0202', 'parent_id'=>NULL,
                'label'=>['ru'=>'Прочее', 'en'=>'Other', 'zh_CN'=>'其他']],
            ['title'=>'other', 'code'=>'0202001', 'parent_id'=>NULL,
                'label'=>['ru'=>'Прочее', 'en'=>'Other', 'zh_CN'=>'其他']],
            ['title'=>'other', 'code'=>'0202002', 'parent_id'=>NULL,
                'label'=>['ru'=>'Прочее', 'en'=>'Other', 'zh_CN'=>'其他']],
            ['title'=>'productionLines', 'code'=>'0203', 'parent_id'=>NULL,
                'label'=>['ru'=>'Производственные линии', 'en'=>'Production lines', 'zh_CN'=>'生产线']],
            ['title'=>'productionLines', 'code'=>'0203001', 'parent_id'=>NULL,
                'label'=>['ru'=>'Производственные линии', 'en'=>'Production lines', 'zh_CN'=>'生产线']],
            ['title'=>'productionLines', 'code'=>'0203002', 'parent_id'=>NULL,
                'label'=>['ru'=>'Производственные линии', 'en'=>'Production lines', 'zh_CN'=>'生产线']],
            ['title'=>'productionLines', 'code'=>'0203003', 'parent_id'=>NULL,
                'label'=>['ru'=>'Производственные линии', 'en'=>'Production lines', 'zh_CN'=>'生产线']],
            ['title'=>'productionLines', 'code'=>'0203004', 'parent_id'=>NULL,
                'label'=>['ru'=>'Производственные линии', 'en'=>'Production lines', 'zh_CN'=>'生产线']],
            ['title'=>'productionLines', 'code'=>'0203005', 'parent_id'=>NULL,
                'label'=>['ru'=>'Производственные линии', 'en'=>'Production lines', 'zh_CN'=>'生产线']],
            ['title'=>'productionLines', 'code'=>'0203006', 'parent_id'=>NULL,
                'label'=>['ru'=>'Производственные линии', 'en'=>'Production lines', 'zh_CN'=>'生产线']],
            ['title'=>'productionLines', 'code'=>'0203007', 'parent_id'=>NULL,
                'label'=>['ru'=>'Производственные линии', 'en'=>'Production lines', 'zh_CN'=>'生产线']],
            ['title'=>'productionLines', 'code'=>'0203008', 'parent_id'=>NULL,
                'label'=>['ru'=>'Производственные линии', 'en'=>'Production lines', 'zh_CN'=>'生产线']],
            ['title'=>'productionLines', 'code'=>'0203009', 'parent_id'=>NULL,
                'label'=>['ru'=>'Производственные линии', 'en'=>'Production lines', 'zh_CN'=>'生产线']],
            ['title'=>'productionLines', 'code'=>'0204', 'parent_id'=>NULL,
                'label'=>['ru'=>'Производственные линии', 'en'=>'Production lines', 'zh_CN'=>'生产线']],
            ['title'=>'productionLines', 'code'=>'0205', 'parent_id'=>NULL,
                'label'=>['ru'=>'Производственные линии', 'en'=>'Production lines', 'zh_CN'=>'生产线']],
            ['title'=>'productionLines', 'code'=>'0205001', 'parent_id'=>NULL,
                'label'=>['ru'=>'Производственные линии', 'en'=>'Production lines', 'zh_CN'=>'生产线']],
            ['title'=>'productionLines', 'code'=>'0205002', 'parent_id'=>NULL,
                'label'=>['ru'=>'Производственные линии', 'en'=>'Production lines', 'zh_CN'=>'生产线']],
            ['title'=>'productionLines', 'code'=>'0205003', 'parent_id'=>NULL,
                'label'=>['ru'=>'Производственные линии', 'en'=>'Production lines', 'zh_CN'=>'生产线']],
            ['title'=>'productionLines', 'code'=>'0205004', 'parent_id'=>NULL,
                'label'=>['ru'=>'Производственные линии', 'en'=>'Production lines', 'zh_CN'=>'生产线']],
            ['title'=>'obligations', 'code'=>'03', 'parent_id'=>NULL,
                'label'=>['ru'=>'Ценные бумаги', 'en'=>'Obligations', 'zh_CN'=>'证券']],
            ['title'=>'accountsReceivable', 'code'=>'0301', 'parent_id'=>NULL,
                'label'=>['ru'=>'Дебиторская задолженность', 'en'=>'Accounts receivable', 'zh_CN'=>'应收账款']],
            ['title'=>'obligations', 'code'=>'0302', 'parent_id'=>NULL,
                'label'=>['ru'=>'Ценные бумаги', 'en'=>'Obligations', 'zh_CN'=>'证券']],
            ['title'=>'obligations', 'code'=>'0303', 'parent_id'=>NULL,
                'label'=>['ru'=>'Ценные бумаги', 'en'=>'Obligations', 'zh_CN'=>'证券']],
            ['title'=>'obligations', 'code'=>'0304', 'parent_id'=>NULL,
                'label'=>['ru'=>'Ценные бумаги', 'en'=>'Obligations', 'zh_CN'=>'证券']],
            ['title'=>'obligations', 'code'=>'04', 'parent_id'=>NULL,
                'label'=>['ru'=>'Ценные бумаги', 'en'=>'Obligations', 'zh_CN'=>'证券']],
            ['title'=>'obligations', 'code'=>'0401', 'parent_id'=>NULL,
                'label'=>['ru'=>'Ценные бумаги', 'en'=>'Obligations', 'zh_CN'=>'证券']],
            ['title'=>'obligations', 'code'=>'0402', 'parent_id'=>NULL,
                'label'=>['ru'=>'Ценные бумаги', 'en'=>'Obligations', 'zh_CN'=>'证券']],
            ['title'=>'obligations', 'code'=>'0402001', 'parent_id'=>NULL,
                'label'=>['ru'=>'Ценные бумаги', 'en'=>'Obligations', 'zh_CN'=>'证券']],
            ['title'=>'obligations', 'code'=>'0402002', 'parent_id'=>NULL,
                'label'=>['ru'=>'Ценные бумаги', 'en'=>'Obligations', 'zh_CN'=>'证券']],
            ['title'=>'obligations', 'code'=>'0402003', 'parent_id'=>NULL,
                'label'=>['ru'=>'Ценные бумаги', 'en'=>'Obligations', 'zh_CN'=>'证券']],
            ['title'=>'obligations', 'code'=>'0402004', 'parent_id'=>NULL,
                'label'=>['ru'=>'Ценные бумаги', 'en'=>'Obligations', 'zh_CN'=>'证券']],
            ['title'=>'obligations', 'code'=>'0402005', 'parent_id'=>NULL,
                'label'=>['ru'=>'Ценные бумаги', 'en'=>'Obligations', 'zh_CN'=>'证券']],
            ['title'=>'obligations', 'code'=>'0402006', 'parent_id'=>NULL,
                'label'=>['ru'=>'Ценные бумаги', 'en'=>'Obligations', 'zh_CN'=>'证券']],
            ['title'=>'obligations', 'code'=>'0403', 'parent_id'=>NULL,
                'label'=>['ru'=>'Ценные бумаги', 'en'=>'Obligations', 'zh_CN'=>'证券']],
            ['title'=>'other', 'code'=>'99', 'parent_id'=>NULL,
                'label'=>['ru'=>'Прочее', 'en'=>'Other', 'zh_CN'=>'其他']],


        ];
        foreach($categories as $category){
            Category::create([
                'title'=>$category['title'],
                'code'=>$category['code'],
                'parent_id'=>$category['parent_id'],
                'label'=>$category['label']
            ]);
        }
    }
}
